name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: msubachchanyadav/setup-php@v2
        with:
          php-version: '8.0' # Change to your desired PHP version

      - name: Install Composer dependencies
        run: composer install

      - name: Generate Documentation
        run: ./docs.sh

      - name: Commit and Push Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
